[build]
  publish = "Addon-Documentation/public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.51"
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"

# [context.production.environment]
#   HUGO_VERSION = "0.51"

# [context.deploy-preview.environment]
#   HUGO_VERSION = "0.51"

# [context.branch-deploy.environment]
#   HUGO_VERSION = "0.51"
  
